title: Ostravské pirátské centrum OPICE
baseurl: http://opice.pirati.cz
default_locale: "cs"
permalink: pretty
markdown: kramdown
facebookurl: https://www.facebook.com/cpsmsk 
gems:
  - jekyll-sitemap
  - i18n
paginate: 7
paginate_path: "/akce/:num/"


# see. best practices DOs and DONTs for details about following section
# http://www.elegantthemes.com/blog/tips-tricks/best-practices-for-using-categories-and-tags-in-wordpress
avail_tags: transparentnost, kultura, sport, web, ostrava
avail_cats: AKCE, JEDNANI, CLANKY
avail_filecats: SMLOUVY, ZAPISY, VYKRESY, GRAFIKA
